version: '2'

services:

  search-devs:
    # Build the search-devs container
    build: .
    # Mount the application root folder to the app root in the container
    volumes:
      - .:/usr/src/app

  nginx:
    # Build the nginx container
    build: ./nginx
    # Map Nginx port 80 to the local machines port 90
    ports:
      - "90:80"
    # Link the client container so that Nginx will have access to it
    links:
      - search-devs
